services:
  localstack:
    image: localstack/localstack:4.7
    container_name: localstack
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    environment:
      - DEBUG=1
      - PERSISTENCE=1
      - SERVICES=ec2,s3,sqs,secretsmanager,iam
    volumes:
      - ./localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
